name: CI

on: [pull_request, push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macOS-latest, windows-latest ]
        include:
          - os: ubuntu-latest
            platform: linux
          - os: macOS-latest
            platform: mac
          - os: windows-latest
            platform: windows
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - run: ./gradlew build test -Pplatform=${{ matrix.platform }} --stacktrace -Pnosign
