name: Release

on:
  workflow_dispatch

jobs:
    create_staging_repository:
      runs-on: ubuntu-latest
      name: Create staging repository
      outputs:
        repository-id: ${{ steps.create.outputs.repository-id }}
      steps:
        - id: create
          uses: nexus-actions/create-nexus-staging-repo@main
          with:
            username: ${{ secrets.ORG_GRADLE_PROJECT_SONATYPEPASSWORD }}
            password: ${{ secrets.ORG_GRADLE_PROJECT_SONATYPEUSERNAME }}
            staging_profile_id: ${{ secrets.SONATYPE_PROFILE_ID }}
            description: ${{ github.repository }}/${{ github.workflow }}#${{ github.run_number }}

    release:
      needs: [create-staging-repository]
      runs-on: ${{ matrix.os }}
      strategy:
        matrix:
          os: [ ubuntu-latest, macOS-latest, windows-latest ]
      env:
        SONATYPE_REPOSITORY_ID: ${{ needs.create_staging_repository.outputs.repository-id }}
        SONATYPE_USERNAME: ${{ secrets.ORG_GRADLE_PROJECT_SONATYPEPASSWORD }}
        SONATYPE_PASSWORD: ${{ secrets.ORG_GRADLE_PROJECT_SONATYPEUSERNAME }}
        GPG_PRIVATE_KEY: ${{ secrets.SIGNING_KEY_ID }}
        GPG_PRIVATE_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
      steps:
        - uses: actions/checkout@v3
        - name: Set up JDK 11
          uses: actions/setup-java@v3
          with:
            java-version: '11'
            distribution: 'adopt'
        - name: Validate Gradle wrapper
          uses: gradle/wrapper-validation-action@v1
        - run: ./gradlew clean build publishAllPublicationsToOss -no-daemon --no-parallel -x test --stacktrace
